"""
Reader Writer constants
"""

# decode_header and write_header
VERSION_LEN_BYTE = 6

# decode_logical_screen_descriptor and write_logical_screen_descriptor
GIF_WIDTH_LEN_BYTE = 2
GIF_HEIGHT_LEN_BYTE = 2
GIF_COLOR_RESOLUTION_LEN_BITS = 3
GIF_GLOBAL_COLOR_TABLE_SIZE_LEN_BITS = 3
DEFAULT_GLOBAL_COLOR_SIZE = 0
GIF_BACKGROUND_COLOR_INDEX_LEN_BYTE = 1
GIF_PIXEL_RATIO_VALUE_LEN_BYTE = 1
NORMALIZED_VALUE = 64
WIDER_RANGE_RATIO = 15

# insert_background_frame
DEFAULT_RESERVED_SIZE = 0
DEFAULT_LOCAL_COLOR_TABLE_SIZE = 0

# decode_application_extension and write_application_extension
APPLICATION_EXTENSION_BLOCK_SIZE_LEN_BYTE = 1
APPLICATION_NAME_LEN_BYTE = 8
APPLICATION_IDENTIFY_LEN_BYTE = 3

# decode_graphic_control_extension and write_graphic_control_extension
GRAPHIC_CONTROL_EXTENSION_BLOCK_SIZE_LEN_BYTE = 1
RESERVED_LEN_BIT = 3
DISPOSAL_LEN_BIT = 3
DELAY_TIME_LEN_BYTE = 2
TRANSPARENT_INDEX_LEN_BYTE = 1
TRANSPARENT_COLOR_FLAG_LEN_BIT = 1
BLOCK_TERMINATOR_LEN_BYTE = 1
BLOCK_TERMINATOR_VALUE = 0

# decode_image_descriptor and write_image
FRAME_LEFT_LEN_BYTE = 2
FRAME_TOP_LEN_BYTE = 2
FRAME_WIDTH_LEN_BYTE = 2
FRAME_HEIGHT_LEN_BYTE = 2
FRAME_INTERLACE_FLAG_LEN_BIT = 1
FRAME_SORT_FLAG_LEN_BIT = 1
FRAME_RESERVED_LEN_BIT = 2
SIZE_LOCAL_COLOR_TABLE_LEN_BIT = 3

# decode_image_data and write_image
LZW_MINIMUM_CODE_SIZE_LEN_BYTE = 1
MAXIMUM_LZW_CS = 12
MINIMUM_LZW_CS = 2
COLOR_TABLE_FLAG_LEN_BYTE = 1

# decode_plain_text and write_plain_text
PLAIN_TEXT_EXTENSION_BLOCK_SIZE_LEN_BYTE = 1
PLAIN_TEXT_LEFT_LEN_BYTE = 2
PLAIN_TEXT_TOP_LEN_BYTE = 2
PLAIN_TEXT_WIDTH_LEN_BYTE = 2
PLAIN_TEXT_HEIGHT_LEN_BYTE = 2
PLAIN_TEXT_CHAR_WIDTH_LEN_BYTE = 1
PLAIN_TEXT_CHAR_HEIGHT_LEN_BYTE = 1
PLAIN_TEXT_TEXT_COLOR_LEN_BYTE = 1
PLAIN_TEXT_BACKGROUND_COLOR_LEN_BYTE = 1

# read_gif and write_gif
BLOCK_PREFIX_LEN_BYTE = 1

# create image
HEX_SIZE = 16
R_START = 1
R_END = G_START = 3
G_END = B_START = 5
B_END = 7

# general
DISPOSAL_OPTION_TWO = 2
DISPOSAL_OPTION_THREE = 3
PENULTIMATE = -2
LAST_ELEMENT = -1
APPLICATION_EXTENSION_BLOCK_SIZE = 11
GRAPHIC_CONTROL_EXTENSION_BLOCK_SIZE = 4
PLAIN_TEXT_EXTENSION_BLOCK_SIZE = 4
END_OF_DATA = 0
BLOCK_SIZE_LEN_BYTE = 1
RGB_LEN_BYTE = 3
TRANSPARENT_VALUE = -1
MIN_TABLE_SIZE = 0
BYTE_MAX_NUMBER = 255

# lzw constants
RESET_SIZE = 4096
MAX_WRITING_SIZE = 12
BYTE_LEN = 8
ZERO = 0
EOI_AND_CC = 2
BINARY_HEADER_LEN = 2

"""
main constants
"""

NUMBER_OF_IMAGE_TO_SHOW = 5
